backend:
  name: github
  repo: zhutou369/ws123 # 请确保这是你的仓库名
  branch: main
  base_url: https://ws-auth-gate.zhutou757.workers.dev # 你的Worker地址

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "blog"
    label: "文章发布"
    folder: "posts"
    create: true
    # 修改下面这一行，加入小时、分钟、秒，确保文件名唯一
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}{{minute}}{{second}}-{{slug}}"
    fields:
      - {label: "文章标题", name: "title", widget: "string"}
      # ... 其他字段保持不变